# Workflow para construir y empaquetar una aplicación Capacitor Android (.apk)

name: Build Android APK (Capacitor)

# El workflow se ejecuta cuando se hace un push a la rama 'main' o manualmente
on:
  push:
    branches:
      - main
      - master # Acepta 'master' por si es el nombre de su rama
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

# Permisos para el CI/CD
permissions:
  contents: read

jobs:
  build_apk:
    # Se ejecuta en un sistema Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js (Necesario para React y Capacitor)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm' 

      # 3. Instalación de Dependencias (Basado en package.json)
      - name: Install Dependencies
        run: npm install

      # 4. Compilación del Código Web (React Build)
      # Crea la carpeta 'build/' con los archivos estáticos optimizados
      - name: Run Web Build
        run: npm run build

      # 5. Instalación de Capacitor (CLI)
      - name: Install Capacitor Core and CLI
        run: npm install @capacitor/cli @capacitor/core
        
      # 6. Crear la Carpeta Nativa Android (Capacitor)
      # Este paso es CRÍTICO. Ejecutamos 'cap add android' y forzamos la creación.
      # Usamos '|| true' para que el workflow no falle si la carpeta ya existía.
      - name: Add Android Platform (Critical Step)
        run: npx cap add android || true 
        
      # 7. Sincronizar el Build Web con el Proyecto Android Nativo
      # Mueve los archivos de 'build/' a 'android/app/src/main/assets/public'
      - name: Sync Web Assets to Android Project
        run: npx cap sync android

      # 8. Configurar el SDK de Android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        
      # 9. Construcción del Proyecto Android con Gradle
      # Se genera el archivo app-debug.apk
      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug

      # 10. Archivar y Subir el APK
      # El APK se guarda como un Artefacto descargable en GitHub
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiAppDespacho-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5
